Update 24.10.yml

diff --git a/.github/workflows/24.10.yml b/.github/workflows/24.10.yml
--- a/.github/workflows/24.10.yml
+++ b/.github/workflows/24.10.yml
@@ -1,4 +1,3 @@
-#
 # Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
 #
 # This is free software, licensed under the MIT License.
@@ -8,7 +7,7 @@
 # Description: Build OpenWrt using GitHub Actions
 #
 
-name: Build_LiBwrt_24_10_AXT-1800
+name: Build_LiBwrt_AXT-1800
 
 on:
   repository_dispatch:
@@ -21,8 +20,7 @@ on:
 
 env:
   REPO_URL: https://github.com/LiBwrt-op/openwrt-6.x.git
-  # REPO_BRANCH: main
-  REPO_BRANCH: 24.10-6.12
+  REPO_BRANCH: openwrt-24.10
   FEEDS_CONF: feeds.conf.default
   CONFIG_FILE: ./config/slate.config
   DIY_P1_SH: ./sh/axt-part1.sh
@@ -37,7 +35,7 @@ env:
 jobs:
   build:
     runs-on: ubuntu-22.04
-    permissions: 
+    permissions:
       contents: write
       actions: write
 
@@ -75,19 +73,10 @@ jobs:
         cd openwrt
         $GITHUB_WORKSPACE/$DIY_P1_SH
 
-    - name: update source
+    - name: Update feeds
       run: cd openwrt && ./scripts/feeds update -a
-      #run: |
-      #  cd openwrt
-      #  sed -i 's|immortalwrt/luci.git|immortalwrt/luci.git^38f7d5cffeb28a49524cb5e0627eec5f0d5e053d|' feeds.conf.default
-      #  ./scripts/feeds update -a
-      #  for pkg in adguardhome autocore automount base-files chinadns-ng cpufreq curl firewall4 fstools \
-      #              luci-app-firewall luci-app-homeproxy luci-app-opkg luci-base luci-mod-network \
-      #              luci-mod-status luci-mod-system opkg ppp sing-box wifi-scripts wireless-regdb; do
-      #    ./scripts/feeds list -r kiddin9 | grep -E "$pkg" | xargs ./scripts/feeds uninstall
-      #  done
 
-    - name: installation source
+    - name: Install feeds
       run: cd openwrt && ./scripts/feeds install -a
 
     - name: Loading Custom Configurations
@@ -142,12 +131,16 @@ jobs:
         name: OpenWrt_bin_${{ steps.compile.outputs.device-name }}_${{ steps.compile.outputs.file-date }}
         path: openwrt/bin
 
-
     - name: Organize documents
       id: organize
       if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
       run: |
-        cd openwrt/bin/targets/*/*
+        FIRMWARE_DIR=$(find openwrt/bin/targets -type d -name "packages")
+        if [ -z "$FIRMWARE_DIR" ]; then
+          echo "FIRMWARE directory not found!"
+          exit 1
+        fi
+        cd "$FIRMWARE_DIR/.."
         rm -rf packages
         echo "FIRMWARE=$PWD" >> $GITHUB_ENV
         echo "status=success" >> $GITHUB_ENV
