Update All_oWRT_24.10.yml

diff --git a/.github/workflows/All_oWRT_24.10.yml b/.github/workflows/All_oWRT_24.10.yml
--- a/.github/workflows/All_oWRT_24.10.yml
+++ b/.github/workflows/All_oWRT_24.10.yml
@@ -141,11 +141,14 @@ jobs:
         sudo mkdir -p /workdir
         sudo chown $USER:$GROUPS /workdir
         
-    - name: Cloning source code
+    - name: Cloning source code and checking out specific commit
       working-directory: /workdir
       run: |
         df -hT $PWD
         git clone --branch $REPO_BRANCH $REPO_URL openwrt
+        cd openwrt
+        git checkout $TARGET_COMMIT || { echo "Failed to checkout commit $TARGET_COMMIT"; exit 1; }
+        echo "Reverted to commit $TARGET_COMMIT successfully"
         ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
 
     - name: Apply custom patches
