Update All_iWRT_25.yml

diff --git a/.github/workflows/All_iWRT_25.yml b/.github/workflows/All_iWRT_25.yml
--- a/.github/workflows/All_iWRT_25.yml
+++ b/.github/workflows/All_iWRT_25.yml
@@ -18,7 +18,7 @@ on:
 env:
   REPO_URL: https://github.com/immortalwrt/immortalwrt.git
   REPO_BRANCH: openwrt-25.12
-  TARGET_COMMIT: b1a74b1cde0dd9b4c07bb5ba7020f94967912f2d
+  #TARGET_COMMIT: b1a74b1cde0dd9b4c07bb5ba7020f94967912f2d
   FEEDS_CONF: feeds.conf.default
   CONFIG_FILE: ./config/WRT.config
   DIY_P1_SH: ./sh/WRT-part1.sh
@@ -150,9 +150,9 @@ jobs:
       run: |
         df -hT $PWD
         git clone --branch $REPO_BRANCH $REPO_URL openwrt
-        cd openwrt
-        git checkout $TARGET_COMMIT || { echo "Failed to checkout commit $TARGET_COMMIT"; exit 1; }
-        echo "Reverted to commit $TARGET_COMMIT successfully"
+        #cd openwrt
+        #git checkout $TARGET_COMMIT || { echo "Failed to checkout commit $TARGET_COMMIT"; exit 1; }
+        #echo "Reverted to commit $TARGET_COMMIT successfully"
         ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
 
     - name: Apply custom patches
