Update All_iWRT_24.10.yml

diff --git a/.github/workflows/All_iWRT_24.10.yml b/.github/workflows/All_iWRT_24.10.yml
--- a/.github/workflows/All_iWRT_24.10.yml
+++ b/.github/workflows/All_iWRT_24.10.yml
@@ -17,7 +17,7 @@ on:
 env:
   REPO_URL: https://github.com/immortalwrt/immortalwrt.git
   REPO_BRANCH: openwrt-24.10
-  #TARGET_COMMIT: 4f7e6e554be2aef6a55be36f9f954d56705eb2ee
+  TARGET_COMMIT: 4f7e6e554be2aef6a55be36f9f954d56705eb2ee
   FEEDS_CONF: feeds.conf.default
   CONFIG_FILE: ./config/WRT.config
   DIY_P1_SH: ./sh/WRT-part1.sh
@@ -147,9 +147,9 @@ jobs:
       run: |
         df -hT $PWD
         git clone --branch $REPO_BRANCH $REPO_URL openwrt
-        #cd openwrt
-        #git checkout $TARGET_COMMIT || { echo "Failed to checkout commit $TARGET_COMMIT"; exit 1; }
-        #echo "Reverted to commit $TARGET_COMMIT successfully"
+        cd openwrt
+        git checkout $TARGET_COMMIT || { echo "Failed to checkout commit $TARGET_COMMIT"; exit 1; }
+        echo "Reverted to commit $TARGET_COMMIT successfully"
         ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
 
     - name: Apply custom patches
