Update All_iWRT_PW.yml

diff --git a/.github/workflows/All_iWRT_PW.yml b/.github/workflows/All_iWRT_PW.yml
--- a/.github/workflows/All_iWRT_PW.yml
+++ b/.github/workflows/All_iWRT_PW.yml
@@ -18,6 +18,7 @@ on:
 env:
   REPO_URL: https://github.com/immortalwrt/immortalwrt.git
   REPO_BRANCH: master
+  TARGET_COMMIT: 71deb5b6d58cf100d0ee7cab23a464a1a5e2eae1
   FEEDS_CONF: feeds.conf.default
   CONFIG_FILE: ./config/WRT.config
   DIY_P1_SH: ./sh/WRT-part1.sh
@@ -130,11 +131,14 @@ jobs:
         sudo mkdir -p /workdir
         sudo chown $USER:$GROUPS /workdir
         
-    - name: Cloning source code
+    - name: Cloning source code and checking out specific commit
       working-directory: /workdir
       run: |
         df -hT $PWD
         git clone --branch $REPO_BRANCH $REPO_URL openwrt
+        cd openwrt
+        git checkout $TARGET_COMMIT || { echo "Failed to checkout commit $TARGET_COMMIT"; exit 1; }
+        echo "Reverted to commit $TARGET_COMMIT successfully"
         ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
 
     - name: Apply custom patches
